id: inaturalist-2019-fgvc6
name: iNaturalist 2019 at FGVC6
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/inaturalist-2019-fgvc6/description.md

dataset:
  answers: inaturalist-2019-fgvc6/prepared/private/answers.csv
  sample_submission: inaturalist-2019-fgvc6/prepared/public/kaggle_sample_submission.csv

grader:
  name: top-1-classification-error
  grade_fn: mlebench.competitions.inaturalist-2019-fgvc6.grade:grade

preparer: mlebench.competitions.inaturalist-2019-fgvc6.prepare:prepare