id: google-quest-challenge
name: Google QUEST Q&A Labeling
competition_type: code
awards_medals: true
prizes:
  - position: 1
    value: 10000
  - position: 2
    value: 7000
  - position: 3
    value: 5000
  - position: 4
    value: 2000
  - position: 5
    value: 1000
description: mlebench/competitions/google-quest-challenge/description.md

dataset:
  answers: google-quest-challenge/prepared/private/test.csv
  sample_submission: google-quest-challenge/prepared/public/sample_submission.csv

grader:
  name: column-wise-spearman
  grade_fn: mlebench.competitions.google-quest-challenge.grade:grade

preparer: mlebench.competitions.google-quest-challenge.prepare:prepare
