id: herbarium-2022-fgvc9
name: Herbarium 2022 - FGVC9
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/herbarium-2022-fgvc9/description.md

dataset:
  answers: herbarium-2022-fgvc9/prepared/private/answers.csv
  sample_submission: herbarium-2022-fgvc9/prepared/public/sample_submission.csv

grader:
  name: macro-f1-score
  grade_fn: mlebench.competitions.herbarium-2022-fgvc9.grade:grade

preparer: mlebench.competitions.herbarium-2022-fgvc9.prepare:prepare