id: siim-covid19-detection
name: SIIM-FISABIO-RSNA COVID-19 Detection
competition_type: code
awards_medals: true
prizes:
  - position: 1
    value: 30000
  - position: 2
    value: 20000
  - position: 3
    value: 10000
  - position: 4
    value: 8000
  - position: 5
    value: 7000
  - position: 6
    value: 5000
  - position: 7
    value: 5000
  - position: 8
    value: 5000
  - position: 9
    value: 5000
  - position: 10
    value: 5000
description: mlebench/competitions/siim-covid19-detection/description.md

dataset:
  answers: siim-covid19-detection/prepared/private/test.csv
  sample_submission: siim-covid19-detection/prepared/public/sample_submission.csv

grader:
  name: mean-average-precision
  grade_fn: mlebench.competitions.siim-covid19-detection.grade:grade

preparer: mlebench.competitions.siim-covid19-detection.prepare:prepare
